# Generated by Django 4.2.4 on 2023-08-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='symbol',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
