# Generated by Django 4.2.4 on 2023-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_outlet', '0003_alter_article_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='symbol',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='market',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='market',
            name='webpage',
            field=models.CharField(max_length=256),
        ),
    ]
