# Generated by Django 4.2.4 on 2023-09-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_outlet', '0004_alter_article_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
