# Generated by Django 4.2.4 on 2023-12-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikea_outlet', '0006_person_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea_outlet.person')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikea_outlet.market')),
            ],
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
